### ISSUE TITLE
Unit tests are not functioning

### ISSUE THREAD

**Issue by thomasbtf** [koesterlab/snakemake-workflow-sars-cov2#65]
See https://github.com/koesterlab/snakemake-workflow-sars-cov2/runs/1928205192?check_suite_focus=true#step:10:120

```
Generating unit tests for each rule...
Generating unit test for rule all: .tests/unit/test_all.py.
Traceback (most recent call last):
  File "/opt/conda/envs/snakemake/lib/python3.9/site-packages/snakemake/__init__.py", line 691, in snakemake
    success = workflow.execute(
  File "/opt/conda/envs/snakemake/lib/python3.9/site-packages/snakemake/workflow.py", line 808, in execute
    unit_tests.generate(
  File "/opt/conda/envs/snakemake/lib/python3.9/site-packages/snakemake/unit_tests/__init__.py", line 89, in generate
    copy_files(job.input, "data")
  File "/opt/conda/envs/snakemake/lib/python3.9/site-packages/snakemake/unit_tests/__init__.py", line 81, in copy_files
    shutil.copytree(f, target)
  File "/opt/conda/envs/snakemake/lib/python3.9/shutil.py", line 557, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/opt/conda/envs/snakemake/lib/python3.9/shutil.py", line 458, in _copytree
    os.makedirs(dst, exist_ok=dirs_exist_ok)
  File "/opt/conda/envs/snakemake/lib/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '.tests/unit/all/data/results/vcf-report'
```

**Comment by thomasbtf** [comment]
not important
