### ISSUE TITLE
ModuleNotFoundError: No module named 'snakemake_wrapper_utils'

### ISSUE THREAD

**Issue by thomasbtf** [koesterlab/snakemake-workflow-sars-cov2#94]
When using wrappers with `get_java_opts` from` snakemake_wrapper_utils.java` sometimes fail. Applies to rules like `quast_unpolished_contigs` and `mark_duplicates`

<details>
<summary>Failed rules</summary>

```
[Fri Mar  5 06:47:39 2021]
rule quast_unpolished_contigs:
    input: resources/genomes/main.fasta, results/2021-02-27/aligned-unpolished-contigs/10667.bam, results/2021-02-27/assembly/10667/10667.contigs.fa
    output: results/2021-02-27/quast-unpolished/10667/report.tsv
    log: logs/2021-02-27/quast/10667.log
    jobid: 183
    wildcards: date=2021-02-27, sample=10667
    threads: 8

Activating conda environment: /home/thomas/repos/snakemake-workflow-sars-cov2/.snakemake/conda/d99362c6
Activating conda environment: /home/thomas/repos/snakemake-workflow-sars-cov2/.snakemake/conda/121c7550
Traceback (most recent call last):
  File "/home/thomas/repos/snakemake-workflow-sars-cov2/.snakemake/scripts/tmpilinfg0h.wrapper.py", line 12, in <module>
    from snakemake_wrapper_utils.java import get_java_opts
ModuleNotFoundError: No module named 'snakemake_wrapper_utils'

[Fri Mar  5 06:47:50 2021]
Error in rule mark_duplicates:
    jobid: 635
    output: results/2021-02-27/dedup/ref~29450/29450.bam, results/2021-02-27/qc/dedup/ref~29450/29450.metrics.txt
    log: logs/2021-02-27/picard/dedup/ref~29450/29450.log (check log file(s) for error message)
    conda-env: /home/thomas/repos/snakemake-workflow-sars-cov2/.snakemake/conda/121c7550

RuleException:
CalledProcessError in line 74 of /home/thomas/repos/snakemake-workflow-sars-cov2/workflow/rules/read_mapping.smk:
Command 'source /home/thomas/mambaforge/bin/activate '/home/thomas/repos/snakemake-workflow-sars-cov2/.snakemake/conda/121c7550'; set -euo pipefail;  python /home/thomas/repos/snakemake-workflow-sars-cov2/.snakemake/scripts/tmpilinfg0h.wrapper.py' returned non-zero exit status 1.
  File "/home/thomas/mambaforge/envs/snakemake5/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 2319, in run_wrapper
  File "/home/thomas/repos/snakemake-workflow-sars-cov2/workflow/rules/read_mapping.smk", line 74, in __rule_mark_duplicates
  File "/home/thomas/mambaforge/envs/snakemake5/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 568, in _callback
  File "/home/thomas/mambaforge/envs/snakemake5/lib/python3.9/concurrent/futures/thread.py", line 52, in run
  File "/home/thomas/mambaforge/envs/snakemake5/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 554, in cached_or_run
  File "/home/thomas/mambaforge/envs/snakemake5/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 2350, in run_wrapper
Job failed, going on with independent jobs.
Select jobs to execute...
Failed to solve scheduling problem with ILP solver. Falling back to greedy solver.Run Snakemake with --verbose to see the full solver output for debugging the problem.
Traceback (most recent call last):
  File "/home/thomas/repos/snakemake-workflow-sars-cov2/.snakemake/scripts/tmptj8mdb_x.wrapper.py", line 12, in <module>
    from snakemake_wrapper_utils.java import get_java_opts
ModuleNotFoundError: No module named 'snakemake_wrapper_utils'

[Fri Mar  5 06:47:50 2021]
Error in rule mark_duplicates:
    jobid: 691
    output: results/2021-02-27/dedup/ref~29452/29452.bam, results/2021-02-27/qc/dedup/ref~29452/29452.metrics.txt
    log: logs/2021-02-27/picard/dedup/ref~29452/29452.log (check log file(s) for error message)
    conda-env: /home/thomas/repos/snakemake-workflow-sars-cov2/.snakemake/conda/121c7550

RuleException:
CalledProcessError in line 74 of /home/thomas/repos/snakemake-workflow-sars-cov2/workflow/rules/read_mapping.smk:
Command 'source /home/thomas/mambaforge/bin/activate '/home/thomas/repos/snakemake-workflow-sars-cov2/.snakemake/conda/121c7550'; set -euo pipefail;  python /home/thomas/repos/snakemake-workflow-sars-cov2/.snakemake/scripts/tmptj8mdb_x.wrapper.py' returned non-zero exit status 1.
  File "/home/thomas/mambaforge/envs/snakemake5/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 2319, in run_wrapper
  File "/home/thomas/repos/snakemake-workflow-sars-cov2/workflow/rules/read_mapping.smk", line 74, in __rule_mark_duplicates
  File "/home/thomas/mambaforge/envs/snakemake5/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 568, in _callback
  File "/home/thomas/mambaforge/envs/snakemake5/lib/python3.9/concurrent/futures/thread.py", line 52, in run
  File "/home/thomas/mambaforge/envs/snakemake5/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 554, in cached_or_run
  File "/home/thomas/mambaforge/envs/snakemake5/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 2350, in run_wrapper
Job failed, going on with independent jobs.
Select jobs to execute...
Failed to solve scheduling problem with ILP solver. Falling back to greedy solver.Run Snakemake with --verbose to see the full solver output for debugging the problem.
Traceback (most recent call last):
  File "/home/thomas/repos/snakemake-workflow-sars-cov2/.snakemake/scripts/tmp5z9qokl3.wrapper.py", line 12, in <module>
    from snakemake_wrapper_utils.java import get_java_opts
ModuleNotFoundError: No module named 'snakemake_wrapper_utils'

[Fri Mar  5 06:47:53 2021]
Error in rule mark_duplicates:
    jobid: 747
    output: results/2021-02-27/dedup/ref~29454/29454.bam, results/2021-02-27/qc/dedup/ref~29454/29454.metrics.txt
    log: logs/2021-02-27/picard/dedup/ref~29454/29454.log (check log file(s) for error message)
    conda-env: /home/thomas/repos/snakemake-workflow-sars-cov2/.snakemake/conda/121c7550

RuleException:
CalledProcessError in line 74 of /home/thomas/repos/snakemake-workflow-sars-cov2/workflow/rules/read_mapping.smk:
Command 'source /home/thomas/mambaforge/bin/activate '/home/thomas/repos/snakemake-workflow-sars-cov2/.snakemake/conda/121c7550'; set -euo pipefail;  python /home/thomas/repos/snakemake-workflow-sars-cov2/.snakemake/scripts/tmp5z9qokl3.wrapper.py' returned non-zero exit status 1.
  File "/home/thomas/mambaforge/envs/snakemake5/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 2319, in run_wrapper
  File "/home/thomas/repos/snakemake-workflow-sars-cov2/workflow/rules/read_mapping.smk", line 74, in __rule_mark_duplicates
  File "/home/thomas/mambaforge/envs/snakemake5/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 568, in _callback
  File "/home/thomas/mambaforge/envs/snakemake5/lib/python3.9/concurrent/futures/thread.py", line 52, in run
  File "/home/thomas/mambaforge/envs/snakemake5/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 554, in cached_or_run
  File "/home/thomas/mambaforge/envs/snakemake5/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 2350, in run_wrapper
Job failed, going on with independent jobs.
Select jobs to execute...
```

</details>

But then, when executing `quast_unpolished_contigs` literally as the next job it works:

```
[Fri Mar  5 06:47:54 2021]
rule quast_unpolished_contigs:
    input: resources/genomes/main.fasta, results/2021-02-27/aligned-unpolished-contigs/29404.bam, results/2021-02-27/assembly/29404/29404.contigs.fa
    output: results/2021-02-27/quast-unpolished/29404/report.tsv
    log: logs/2021-02-27/quast/29404.log
    jobid: 213
    wildcards: date=2021-02-27, sample=29404
    threads: 8

Removing temporary output file results/2021-02-27/aligned-unpolished-contigs/10667.bam.
[Fri Mar  5 06:47:54 2021]
Finished job 183.
96 of 907 steps (11%) done
```

**Comment by thomasbtf** [comment]
Just works with 6.0.2
